### ISSUE TITLE
setTags method missing

### ISSUE THREAD

**Issue by solvingj** [Danielku15/swagger-codegen-cpprestsdk#1] opened 2017-06-17 16:18 UTC
I posted the ticket below, but since you were the original author I thought I might be able to get you to take a look by posting here: 

https://github.com/swagger-api/swagger-codegen/issues/5862

Any ideas?

**Comment by Danielku15** [comment] 2017-07-09 11:33
Sorry for the delayed answer. The cpprestsdk codegen evolved quite a bit since it was initially merged into the official project. But since the problem is already resolved I think there is no need for further discussion here :smile:

**Closed as completed by Danielku15** 2017-07-09 11:33 UTC
